name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  checks: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Run tests with pytest and generate report
      run: |
        pytest --maxfail=1 --disable-warnings --junitxml=test-report.xml
          
    - name: Upload Test Results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-report.xml

    - name: Publish Test Report (optional)
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # Run always, even if tests fail
      with:
        report_paths: '**/test-report.xml'  
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sj-images:my-calculator-app .
        
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/sj-images:my-calculator-app

  deploy_to_instance:
    needs: build_and_test
    runs-on: ubuntu-latest
      
    steps:
    - name: SSH into Instance and Update Docker Container
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-calculator-app:latest
          docker stop my-calculator-app || true
          docker rm my-calculator-app || true
          docker run -d --name my-calculator-app -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/my-calculator-app:latest
      